[package]
edition = "2021"
name = "probably_filters"
version = "0.1.0"

[dependencies]
fasthash = "0.4.0"
rand = "0.8.5"
thiserror = "1.0.62"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
harness = false
name = "bench_cbf"

[[bench]]
harness = false
name = "bench_cuckoo"
